build:
  - "**/*.gradle"
  - "**/*.gradle.kts"

ci:
  - ".github/*"
  
compiler-plugin:
  - "compiler-plugin/src/**/*"
  
documentation:
  - "docs/*.md"

ktorfit-gradle-plugin:
  - "ktorfit-gradle-plugin/src/**/*"
  
ktorfit-ksp:
  - "ktorfit-ksp/src/**/*"  

ktorfit-lib:
  - "ktorfit-lib/src/**/*"
  - "ktorfit-lib-core/src/**/*"

sandbox:
  - "sandbox/src/**/*"  
